# fotmat() 함수로 숫자를 문자열로 변환하기
#format_a= "{}만 원".format(5000)
#format_b= "파이썬 열공해서 첫 연봉 {}만 원 만들기" .format(5000)
#format_c="{} {} {}" .format(3000,4000,5000)
#format_d="{} {} {}" .format(1,"문자열",True)
#rint(format_a)
#print(format_b)
#print(format_c)
#print(format_d)

output_a = "{:d}" .format(52)
output_b = "{:5d}" .format(52)
output_c = "{:10d}" .format(52)

output_d = "{:05d}" .format(52)
output_e = "{:05d}" .format(-52)
print("# 기본")
print(output_a)
print("# 특정칸에 출력")
print(output_b)
print(output_c)
print("# 빈칸을 0으로")
print(output_d)
print(output_e)
print()
print()
print()
output_f = "{:+d}" .format(52)
print(output_f)
print()
print()
